In [2]:
import numpy as np

In [3]:
arr1 = np.arange(1,11,1)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr2 = np.arange(2,21,2)
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr3 =np.zeros(10)
arr3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
arr4 =np.ones(15)
arr4

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
arr5 = np.eye(4,4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
arr6 = np.full((3,5),8)
arr6

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [9]:
arr7 = np.linspace(5,50,20) 
arr7

array([ 5.        ,  7.36842105,  9.73684211, 12.10526316, 14.47368421,
       16.84210526, 19.21052632, 21.57894737, 23.94736842, 26.31578947,
       28.68421053, 31.05263158, 33.42105263, 35.78947368, 38.15789474,
       40.52631579, 42.89473684, 45.26315789, 47.63157895, 50.        ])

In [ ]:
arr8 = np.random.rand(3,4)
arr8

576


In [11]:
arr9 = np.random.randint(1,101,size=(4,4))
arr9

array([[81, 31,  5, 31],
       [38, 77, 82, 35],
       [72, 29, 88, 94],
       [21, 88, 94,  6]], dtype=int32)

In [12]:
print(arr9.shape)
print(arr9.size)
print(arr9.dtype)
print(arr9.ndim)

(4, 4)
16
int32
2


In [13]:
arr11 = np.arange(1,13,1)
print(arr11)
arr11 = arr11.reshape(3,4)
arr11

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
arr12 = np.arange(1,21).reshape(4,5)
print(arr12)
arr12 = arr12.reshape(-1)
arr12

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
arr13 = np.arange(1,10).reshape(3,3)
print(arr13)

print(arr13[0][0]) 
print(arr13[2][2]) 
print(arr13[1][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
5


In [16]:
arr14 = np.arange(1,26).reshape(5,5)
print(arr14)
print(arr14[0:3])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [17]:
print(arr14[:,-2:])

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [18]:
arr14[arr14>20]=100
arr14

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [100, 100, 100, 100, 100]])

In [19]:
count = np.sum(arr14>50)
count

np.int64(5)

In [20]:
arr14[arr14%2==0]=True
arr14

array([[ 1,  1,  3,  1,  5],
       [ 1,  7,  1,  9,  1],
       [11,  1, 13,  1, 15],
       [ 1, 17,  1, 19,  1],
       [ 1,  1,  1,  1,  1]])

In [21]:
arr19 =np.arange(1,50)
arr19[arr19%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [22]:
arr19[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

# Question 21-40


In [23]:
arr21 = np.arange(1,11)
arr21_1=np.arange(11,21)
print(arr21+arr21_1)
print(arr21-arr21_1)
print(arr21*arr21_1)
print(arr21%arr21_1)

[12 14 16 18 20 22 24 26 28 30]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[ 11  24  39  56  75  96 119 144 171 200]
[ 1  2  3  4  5  6  7  8  9 10]


In [24]:
arr22 = np.arange(1,50)
print(np.sqrt(arr22))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.35889894 4.47213595 4.58257569 4.69041576 4.79583152 4.89897949
 5.         5.09901951 5.19615242 5.29150262 5.38516481 5.47722558
 5.56776436 5.65685425 5.74456265 5.83095189 5.91607978 6.
 6.08276253 6.164414   6.244998   6.32455532 6.40312424 6.4807407
 6.55743852 6.63324958 6.70820393 6.78232998 6.8556546  6.92820323
 7.        ]


In [25]:
print(np.mean(arr22))
print(np.median(arr22))
print(np.std(arr22))
print(np.var(arr22))

25.0
25.0
14.142135623730951
200.0


In [26]:
print(np.max(arr22))
print(np.min(arr22))

49
1


In [27]:
arr25 = np.arange(1,10).reshape(3,3)
print(arr25)
print(np.sum(arr25,axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]


In [28]:
print(np.cumsum(arr25))

[ 1  3  6 10 15 21 28 36 45]


In [29]:
arr27 = np.random.randint(100,200,10)
print(arr27)
print(np.sort(arr27))


[135 127 187 182 103 121 122 101 179 141]
[101 103 121 122 127 135 141 179 182 187]


In [30]:
arr28 = np.arange(1,10).reshape(3,3)
print(arr28)
print(np.sum(arr28,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 6 15 24]


In [31]:
print(np.argmax(arr28))

8


In [32]:
# Question 30

In [33]:
arr31 = np.arange(1,10).reshape(3,3)
arr31_1=np.arange(11,20).reshape(3,3)
print(np.vstack((arr31,arr31_1)))
print(np.hstack((arr31,arr31_1)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [34]:
arr34 = np.zeros((4,4))
arr34[::2,::2]=1
arr34[1::2,1::2]=1
arr34

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [35]:
arr35 = np.arange(1,10).reshape(3,3)
arr35

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr36 =np.arange(10,100,10).reshape(3,3)
arr36

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [40]:

arr38 = np.array([10, 3, 7, 12, 17, 20, 23, 25, 29])

prime_numbers = []

for num in arr38:
    if num > 1:
        for i in range(2, int(np.sqrt(num)) + 1):
            if num % i == 0:
                break
        else:
            prime_numbers.append(num)
print(prime_numbers)

[np.int64(3), np.int64(7), np.int64(17), np.int64(23), np.int64(29)]


In [41]:
arr39 = np.array([10, -3, 7, 12, -17, 20, -23, 25, 29])
arr39[arr39 < 0] = 0
arr39

array([10,  0,  7, 12,  0, 20,  0, 25, 29])

In [ ]:
#frequency of each element in the array
arr40 = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
uni = np.unique(arr40)

np.int64(10)